postgres:
  connectTimeout: 5s
  maxConns: 10
  minConns: 2
  maxConnLifeTime: 2h
  maxConnIdleTime: 15m
  sslMode: "disable"

http:
  host: 0.0.0.0
  port: 8080
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s
